---
- name: Install docker
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop: "{{ docker }}"

# - name: Install Docker Module for Python
#   pip:
#     name: docker

- name: enable docker systemd service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: adding existing user {{ user }} to group docker
  become: yes
  user:
    name: "{{ item }}"
    groups: ["docker"]
    append: yes
  with_items: "{{ user }}"

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

